export default {
	products: [
		{
			_id: '123',
			name: 'Slim Shirt',
			image: '/images/d1.jpg',
			price: 60,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
		},
		{
			_id: '234',
			name: 'Fit Shirt',
			image: '/images/d1.jpg',
			price: 60,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
		},
		{
			_id: '678',
			name: 'Sweat Shirt',
			image: '/images/d1.jpg',
			price: 60,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
		},
		{
			_id: '456',
			name: 'Slim Shirt',
			image: '/images/d1.jpg',
			price: 60,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
		},
		{
			_id: '768',
			name: 'Slim Shirt',
			image: '/images/d1.jpg',
			price: 60,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
		},
	],
};
